version: '3.8'

services:
  # AIGC MCP 客户端
  mcp-client:
    build: .
    container_name: pixel-mcp-client
    ports:
      - "9003:9003"
    volumes:
      - ./data:/data
    env_file:
      - .env
      - .env.local
    environment:
      - CHAINLIT_HOST=0.0.0.0
      - CHAINLIT_PORT=9003
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9003/health"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped 