version: '3.8'

services:
  # MinIO 对象存储（S3兼容）
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    ports:
      - "9000:9000"  # API 端口
      - "9001:9001"  # Web 控制台端口
    volumes:
      - ./data/minio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  # MinIO 初始化（创建Bucket）
  minio-init:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_USERNAME} ${MINIO_PASSWORD};
      /usr/bin/mc mb myminio/${MINIO_BUCKET} --ignore-existing;
      /usr/bin/mc anonymous set public myminio/${MINIO_BUCKET};
      exit 0;
      "
    restart: "no"

  # AIGC MCP 服务
  mcp-server:
    build: .
    depends_on:
      minio:
        condition: service_healthy
      minio-init:
        condition: service_completed_successfully
    ports:
      - "9002:9002"
    volumes:
      - ./data:/data
    env_file:
      - .env
      - .env.local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9001/health"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
